# Generated by Django 4.2.16 on 2025-05-16 13:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs_post',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('P_date', models.DateField(auto_now_add=True)),
                ('E_date', models.DateTimeField(auto_now_add=True)),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
            ],
        ),

    ]
