# Generated by Django 4.2.16 on 2025-05-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs_post',
            name='E_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobs_post',
            name='P_date',
            field=models.DateField(),
        ),
    ]
